### ISSUE TITLE
Add new recipes: ecomm customers who viewed x also viewed

### ISSUE THREAD

**Issue by theachoem** [vtenh/ml#104]
- [ ] aws-ecomm-customers-who-viewed-x-also-viewed
- [ ] aws-ecomm-frequently-bought-together
- [ ] aws-ecomm-recommended-for-you

**Comment by theachoem** [comment]
```
botocore.errorfactory.InvalidInputException: An error occurred (InvalidInputException) when calling the CreateSolution operation: This recipe with ARN arn:aws:personalize:::recipe/aws-ecomm-customers-who-viewed-x-also-viewed is unsupported. Please use the supported recipes listed at https://docs.aws.amazon.com/personalize/latest/dg/working-with-predefined-recipes.html
```

**Comment by theachoem** [comment]
## Error when creating a recommender:
Since we didn't create our dataset group with the specific domain 'ECOMMERCE'|'VIDEO_ON_DEMAND', we also can't create recommenders.
```shell
(base) theachoem@dev-2 ml % /opt/anaconda3/bin/python /Users/theachoem/Coding/Pythons/ml/main.py
{
    "name": "customers_who_viewed_x_also_viewed",
    "recipeArn": "arn:aws:personalize:::recipe/aws-ecomm-customers-who-viewed-x-also-viewed",
    "datasetGroupArn": "arn:aws:personalize:ap-southeast-1:611922433325:dataset-group/vtenh-ml-lab-dsg"
}
Traceback (most recent call last):
  File "/Users/theachoem/Coding/Pythons/ml/main.py", line 26, in <module>
    RecommenderCreator().call()
  File "/Users/theachoem/Coding/Pythons/ml/aws_cloud/recommender_creator.py", line 25, in call
    self.create_recommenders()
  File "/Users/theachoem/Coding/Pythons/ml/aws_cloud/recommender_creator.py", line 30, in create_recommenders
    self.create_recommender_for(recommender)
  File "/Users/theachoem/Coding/Pythons/ml/aws_cloud/recommender_creator.py", line 36, in create_recommender_for
    response = self.personalize.create_recommender(**kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidInputException: An error occurred (InvalidInputException) when calling the CreateRecommender operation: Please use a domain-specific Dataset Group to create the Recommender
```

## Solution:
Recreate dataset group which specific domain. 'ECOMMERCE'.
<img width="600px" src="https://user-images.githubusercontent.com/29684683/144962143-37b4996e-bba0-4610-9fb7-19955756a27d.png" />
